apiVersion: v1
kind: Service
metadata:
  name: sample_app_service
spec:
  type: NodePort
  selector:
    app: sample_app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080

